version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: prod_explorer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
